version: '3'

services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/conf.d:/etc/nginx/conf.d
      - ./volumes/certs:/etc/nginx/certs
      - ./volumes/logs:/var/log/nginx
    restart: unless-stopped
#    networks:
#      - nginx-network

#networks:
#  nginx-network:
#    driver: bridge